# Generated by Django 6.0.1 on 2026-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=200, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
