# Generated by Django 6.0.1 on 2026-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['topic'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['fullname'], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
    ]
