# Generated by Django 6.0.1 on 2026-01-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailings",
            name="manually_changed",
            field=models.BooleanField(default=False, verbose_name="Ручное управление"),
        ),
    ]
