# Generated by Django 6.0.1 on 2026-01-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailings_manually_changed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailings",
            old_name="manually_changed",
            new_name="manually_controlled",
        ),
    ]
