# Generated by Django 6.0.1 on 2026-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='recipients',
            field=models.ManyToManyField(related_name='mailings', to='mailing.recipient', verbose_name='Получатели'),
        ),
    ]
